Refactor/user
COS301-SE-2024/ClassConnect pull request #158
Opened 2024-08-01 09:57 UTC by Ashley-Kapaso

# Pull Request

**Description:**

Remove user redundant CRUD functionality

**Type of Change:**

- [x] Refactoring

2024-08-01 15:02 UTC, bukhosi-eugene-mpande requested changes
Thank you for the code reduction the changes look good can you please put the utils in the server folder so that they can't be imported in to the client side :
https://kit.svelte.dev/docs/project-structure

2024-08-01 17:19 UTC, Ashley-Kapaso commented
Great idea will start working on it.

2024-08-06 14:25 UTC, bukhosi-eugene-mpande approved these changes

2024-08-06 17:48 UTC, ayandajuqu approved these changes
I see how you've restructured your utils for sending the emails and how youve joined the different user actions we had to one.. Very useful :)

2024-08-06 20:06 UTC, merged